CC = gcc
CFLAGS = -Wall -g

SRC_FILES = q1.c q2.c q3.c q4.c q5-1.c q5-2.c q6.c q7.c q8.c
EXEC_FILES = q1 q2 q3 q4 q5-1 q5-2 q6 q7 q8

all: $(EXEC_FILES)

q1: q1.c
	$(CC) $(CFLAGS) q1.c -o q1

q2: q2.c
	$(CC) $(CFLAGS) q2.c -o q2

q3: q3.c
	$(CC) $(CFLAGS) q3.c -o q3

q4: q4.c
	$(CC) $(CFLAGS) q4.c -o q4

q5-1: q5-1.c
	$(CC) $(CFLAGS) q5-1.c -o q5-1

q5-2: q5-2.c
	$(CC) $(CFLAGS) q5-2.c -o q5-2

q6: q6.c
	$(CC) $(CFLAGS) q6.c -o q6

q7: q7.c
	$(CC) $(CFLAGS) q7.c -o q7

q8: q8.c
	$(CC) $(CFLAGS) q8.c -o q8

clean:
	rm -f $(EXEC_FILES)
